name: update-notifier

env:
  REPO_URL: https://github.com/${{github.repository}}
  ACTOR: ${{github.actor}}

on: 
  push:
    branches:
      - main

jobs:
  notify-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Notify Discord
      uses: rjstone/discord-webhook-notify@v1
      with: 
        severity: info
        username: ${{env.ACTOR}}
        color: '#a31780'
        text: Repo Update!
        description: Changes to the main branch of the repo have been made!
        details: '${{fromJSON(toJSON(github.event.commits)).length}} commits have been pushed to the main branch at ${{env.REPO_URL}}. Head commit message: ${{github.event.head_commit.message}}'
        webhookUrl: ${{secrets.DISCORD_WEBHOOK}}

